### ISSUE TITLE
whmcs broke this great addon 

### ISSUE THREAD

**Issue by beals1pt0** [craftyshaun/whmcs-grouppay#9]
is there any chance of someone  bringing  life back to this great addon

**Comment by craftyshaun** [comment]
I don't have a recent install of WHMCS installed but what specifically has broken ?
Is it something small or is the whole addon in a pile of flames ?

**Comment by beals1pt0** [comment]
well it was giving white pages with php errors i reverted back to 5.3.1.4


On Thu, Jul 23, 2015 at 10:48 PM, Shaun D <notifications@github.com> wrote:

> I don't have a recent install of WHMCS installed but what specifically has
> broken ?
> Is it something small or is the whole addon in a pile of flames ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/craftyshaun/whmcs-grouppay/issues/9#issuecomment-124297971>
> .
>



-- 
[image: Havens Hosting] <https://havenshosting.com/index.php>

**Comment by DougK94** [comment]
if it helps, dbconnect.php was removed from v6.0 

http://docs.whmcs.com/Version_6.0.0_..._Dbconnect.php

Removal of Dbconnect.php

6.0 sees the removal of the dbconnect.php file from the root WHMCS directory. This file has been deprecated since WHMCS Version 5.2 and has remained only for backwards compatibility with older modules. As of 6.0 however, any scripts which still rely on including the dbconnect.php file to function will need to be updated to instead include the init.php file. When including the init.php file, it is not necessary to include any other WHMCS files.

For reference, the most up-to-date code sample for creating your own custom client area pages which works in WHMCS 5.3.0 and later is available @ http://docs.whmcs.com/Creating_Pages

**Comment by trunkspacehosting** [comment]
Was there any update to this? Grouppay will no longer work for WHMCS 6.0, and this is the sole reason why we are not updating our WHMCS installation

When you access WHMCS_ROOT/grouppay.php in WHMCS6, you see:
 Fatal error: Cannot redeclare initialiseclientarea() in <WHMCS_ROOT>/includes/clientareafunctions.php on line 29

**Comment by sixteeN11** [comment]
Update?

**Comment by christopherftw09** [comment]
I am currently in the middle of rewriting parts of the module to work with whmcs v6. I will fork request it here once I'm finished.

**Comment by craftyshaun** [comment]
A pull request has just been merged that addresses the whmcs 6.0 issues

**Comment by beals1pt0** [comment]
i have installed the latest update when i click on clanpay link it doesn't open up the old way did i miss something

**Comment by beals1pt0** [comment]
works thank you

**Comment by trunkspacehosting** [comment]
Wanted to say thank you as well! Works great on WHMCS 6.0.1

**Comment by JHulsmans** [comment]
Not a problem at all. The least I could do for an already exquisite add-on.


Kind regards

Joni Hulsmans

2015-12-06 7:13 GMT+01:00 trunkspacehosting <notifications@github.com>:
